"""Add user token fields

Revision ID: 901aa7dc0f8d
Revises: dda44bde7009
Create Date: 2019-07-01 20:52:27.005488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901aa7dc0f8d'
down_revision = 'dda44bde7009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
